#pragma config(Sensor, S3,ts,             sensorEV3_Touch)
#pragma config(Motor,  motorB,          wm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          fm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int n = 0;

void water(){

		sleep(1);
		setMotorSpeed(wm, 30);
		sleep(500);
		setMotorSpeed(wm, 0);
		sleep(2000);
		setMotorSpeed(wm, -30);
		sleep(500);
		setMotorSpeed(wm, 0);
}

void food(){
    
		setMotorSpeed(fm,-15);
		sleep(2000);
		setMotorSpeed(fm, 0);
		sleep(4000);
		setMotorSpeed(fm,15);
		sleep(1000);

}

task main()
{
	while(1){
		while(getTouchValue(ts) == 0){
			sleep(500);
			displayBigTextLine(2,"n = %d",n);
			n++;
			if(n == 10){
				food();
				water();
				n = 0;
			}
		}
		while(getTouchValue(ts) == 1){
			water();
		}
	}
}
